import React, { useState } from 'react';
import SwissChart from './SwissChart';
import CitationFooter from './CitationFooter';
import html2canvas from 'html2canvas';
import { Download, Loader2 } from 'lucide-react';

const SwissInfographic = ({ data = {} }) => {
  const [isDownloading, setIsDownloading] = useState(false);

  if (!data) return null;

  const safeStats = data.stats || [];
  const safeDate = data.date || new Date().toLocaleDateString();
  const safeSummary = data.executive_summary || "Generating insights...";
  const safeReferences = data.references || ["Data generated by AI"];
  const safeChartData = data.chartData || [];
  const safeTitle = data.title || "Infographic Report";
  const safeVerifyUrl = data.content?.source_url || window.location.href;


  const handleDownload = async () => {
    setIsDownloading(true);
    const element = document.getElementById('infographic-capture');

    if (element) {
      try {
        const canvas = await html2canvas(element, {
          scale: 2,
          backgroundColor: '#F5F5F7',
          logging: false,
          useCORS: true,
          // Fixing the capture size to prevent scrollbar capture
          windowWidth: element.scrollWidth,
          windowHeight: element.scrollHeight
        });

        const link = document.createElement('a');
        link.download = `InfographPro_${safeDate.replace(/\//g, '-')}.png`;
        link.href = canvas.toDataURL('image/png');
        link.click();
      } catch (error) {
        console.error("Download failed:", error);
      }
    }
    setIsDownloading(false);
  };

  return (
    <div className="w-full max-w-[1400px] mx-auto">

      {/* TOOLBAR */}
      <div className="flex justify-end mb-4 px-4 md:px-6">
        <button
          onClick={handleDownload}
          disabled={isDownloading}
          className="flex items-center gap-2 bg-black text-white px-6 py-3 font-mono text-xs uppercase hover:bg-swiss-red transition-colors disabled:opacity-50 w-full md:w-auto justify-center"
        >
          {isDownloading ? (
            <>
              <Loader2 className="animate-spin" size={16} />
              Processing...
            </>
          ) : (
            <>
              <Download size={16} />
              Download Report as PNG
            </>
          )}
        </button>
      </div>

      {/* CAPTURE ZONE */}
      {/* Added overflow-hidden here to act as a master failsafe against horizontal scrolling */}
      <div
        id="infographic-capture"
        className="w-full bg-swiss-offwhite p-4 md:p-8 font-sans text-swiss-black border-2 border-gray-100 shadow-2xl overflow-hidden"
      >

        {/* HEADER */}
        <header className="border-b-4 border-swiss-black pb-8 mb-8">
          <div className="flex flex-col lg:flex-row justify-between items-start gap-4">
            <h1 className="text-3xl lg:text-5xl font-black tracking-tighter uppercase leading-none max-w-3xl break-words">
              {safeTitle}
            </h1>
            <div className="text-left lg:text-right min-w-fit mt-2 lg:mt-0">
              <p className="font-mono text-xs tracking-widest uppercase opacity-60">Generated Report</p>
              <p className="font-mono text-xs mt-1 font-bold">{safeDate}</p>
            </div>
          </div>
        </header>

        {/* MAIN CONTENT */}
        {/* flex-col for mobile, lg:flex-row for desktop. lg:flex-nowrap ensures it stays in a row on big screens */}
        <div className="flex flex-col lg:flex-row lg:flex-nowrap items-stretch mt-8 border-t-4 border-black pt-8 gap-8 lg:gap-16">

          {/* LEFT COLUMN - SIDEBAR */}
          {/* w-full on mobile, fixed 350px on desktop */}
          <div className="w-full lg:w-[350px] shrink-0 flex flex-col gap-8">
            <div
              className="border-2 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] bg-white"
              style={{ padding: '32px' }}
            >
              <h3 className="text-blue-600 font-bold uppercase tracking-widest mb-4 text-[10px]">
                EXECUTIVE BRIEF
              </h3>
              <p className="font-serif text-md leading-relaxed text-gray-900">
                {safeSummary}
              </p>
            </div>

            <div className="grid grid-cols-1 gap-4 mt-6">
              {safeStats.map((stat, i) => (
                <div
                  key={i}
                  className="shadow-[4px_4px_0px_0px_rgba(0,0,0,0.2)] border border-black"
                  style={{
                    backgroundColor: 'black',
                    color: 'white',
                    padding: '24px'
                  }}
                >
                  <p className="text-[10px] uppercase tracking-widest opacity-80 mb-2 border-b border-gray-600 pb-2">
                    {stat.label}
                  </p>
                  <p className="text-4xl font-bold font-mono mt-1">
                    {stat.value}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* RIGHT COLUMN - CHART */}
          {/* grow takes remaining space, min-w-0 prevents flex items from overflowing */}
          <div
            className="w-full grow min-w-0 border-2 border-black flex flex-col relative bg-white"
            style={{ padding: '32px' }}
          >
            <div className="flex justify-between items-end mb-4 border-b-2 border-black pb-2 z-10 relative">
              <h3 className="font-bold uppercase text-xl">Data Analysis</h3>
              <span className="text-xs font-mono uppercase opacity-50">Figure 1.1</span>
            </div>

            <div className="w-full h-[400px] lg:h-[500px] relative overflow-hidden pt-8">
              <SwissChart data={safeChartData} />
            </div>
          </div>

        </div>

        {/* FOOTER SECTION */}
        {/* Added overflow-x-hidden and max-w-full to contain the QR code */}
        <div className="w-full mt-8 overflow-x-hidden max-w-full">
          <CitationFooter
            references={safeReferences}
            date={safeDate}
            verifyUrl={safeVerifyUrl}
          />
        </div>

      </div>
    </div>
  );
};

export default SwissInfographic;