import React, { useState } from 'react';
import SwissChart from './SwissChart';
import CitationFooter from './CitationFooter';
import html2canvas from 'html2canvas';
import { Download, Loader2 } from 'lucide-react';

const SwissInfographic = ({ data = {} }) => {
  const [isDownloading, setIsDownloading] = useState(false);

  if (!data) return null;

  const safeStats = data.stats || [];
  const safeDate = data.date || new Date().toLocaleDateString();
  const safeSummary = data.executive_summary || "Generating insights...";
  const safeReferences = data.references || ["Data generated by AI"];
  const safeChartData = data.chartData || [];
  const safeTitle = data.title || "Infographic Report";

  const handleDownload = async () => {
    setIsDownloading(true);
    const element = document.getElementById('infographic-capture');
    
    if (element) {
      try {
        const canvas = await html2canvas(element, {
          scale: 2,
          backgroundColor: '#F5F5F7',
          logging: false,
          useCORS: true,
        });

        const link = document.createElement('a');
        link.download = `InfographPro_${safeDate.replace(/\//g, '-')}.png`;
        link.href = canvas.toDataURL('image/png');
        link.click();
      } catch (error) {
        console.error("Download failed:", error);
      }
    }
    setIsDownloading(false);
  };

  return (
    <div className="w-full max-w-[1400px] mx-auto">
      
      {/* TOOLBAR */}
      <div className="flex justify-end mb-4 px-6">
        <button
          onClick={handleDownload}
          disabled={isDownloading}
          className="flex items-center gap-2 bg-black text-white px-6 py-3 font-mono text-xs uppercase hover:bg-swiss-red transition-colors disabled:opacity-50"
        >
          {isDownloading ? (
            <>
              <Loader2 className="animate-spin" size={16} />
              Processing...
            </>
          ) : (
            <>
              <Download size={16} />
              Download Report as PNG
            </>
          )}
        </button>
      </div>

      {/* CAPTURE ZONE */}
      <div 
        id="infographic-capture" 
        className="w-full bg-swiss-offwhite p-8 font-sans text-swiss-black border-2 border-gray-100 shadow-2xl"
      >
        
        {/* HEADER */}
        <header className="border-b-4 border-swiss-black pb-8 mb-8">
        
          <div className="flex justify-between items-start gap-4">
            <h1 className="text-5xl font-black tracking-tighter uppercase leading-none max-w-3xl">
              {safeTitle}
            </h1>
            <div className="text-right min-w-fit">
              <p className="font-mono text-xs tracking-widest uppercase opacity-60">Generated Report</p>
              <p className="font-mono text-xs mt-1 font-bold">{safeDate}</p>
            </div>
          </div>
        </header>

        {/* MAIN CONTENT */}
        <div className="flex flex-row items-stretch mt-8 border-t-4 border-black pt-8">

          {/* LEFT COLUMN */}
          <div className="w-[350px] shrink-0 flex flex-col gap-8">
            <div 
              className="border-2 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] bg-white"
              style={{ padding: '32px' }} 
            >
              <h3 className="text-blue-600 font-bold uppercase tracking-widest mb-4 text-[10px]">
                EXECUTIVE BRIEF
              </h3>
              <p className="font-serif text-md leading-relaxed text-gray-900">
                {safeSummary}
              </p>
            </div>

            <div className="flex flex-col gap-4 mt-6">
              {safeStats.map((stat, i) => (
                <div 
                  key={i} 
                  className="shadow-[4px_4px_0px_0px_rgba(0,0,0,0.2)] border border-black"
                  style={{ 
                    backgroundColor: 'black', 
                    color: 'white', 
                    padding: '24px' 
                  }} 
                >
                  <p className="text-[10px] uppercase tracking-widest opacity-80 mb-2 border-b border-gray-600 pb-2">
                    {stat.label}
                  </p>
                  <p className="text-4xl font-bold font-mono mt-1">
                    {stat.value}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* SPACER */}
          <div className="w-16 shrink-0"></div>

          {/* RIGHT COLUMN */}
          <div 
            className="grow min-w-0 border-2 border-black flex flex-col relative bg-white"
            style={{ padding: '32px' }} 
          >
            <div className="flex justify-between items-end mb-4 border-b-2 border-black pb-2 z-10 relative">
               <h3 className="font-bold uppercase text-xl">Data Analysis</h3>
               <span className="text-xs font-mono uppercase opacity-50">Figure 1.1</span>
            </div>
            
            <div className="w-full h-[500px] relative overflow-hidden pt-8">
               <SwissChart data={safeChartData} />
            </div>
          </div>

        </div>

        {/* FOOTER SECTION */}
        <div className="w-full">
          <CitationFooter references={safeReferences} date={safeDate} />
        </div>

      </div>
    </div>
  );
};

export default SwissInfographic;